<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert([
            ['name' => 'AFGHANISTAN'],
            ['name' => 'ALBANIA'],
            ['name' => 'ALGERIA'],
            ['name' => 'ANDORRA'],
            ['name' => 'ANGOLA'],
            ['name' => 'ANGUILLA'],
            ['name' => 'ANTARCTICA'],
            ['name' => 'ARGENTINA'],
            ['name' => 'ARMENIA'],
            ['name' => 'ARUBA'],
            ['name' => 'AUSTRALIA'],
            ['name' => 'AUSTRIA'],
            ['name' => 'AZERBAIJAN'],
            ['name' => 'BAHAMAS'],
            ['name' => 'BAHRAIN'],
            ['name' => 'BANGLADESH'],
            ['name' => 'BARBADOS'],
            ['name' => 'BELARUS'],
            ['name' => 'BELGIUM'],
            ['name' => 'BELIZE'],
            ['name' => 'BENIN'],
            ['name' => 'BERMUDA'],
            ['name' => 'BHUTAN'],
            ['name' => 'BOLIVIA'],
            ['name' => 'BOTSWANA'],
            ['name' => 'BRAZIL'],
            ['name' => 'BULGARIA'],
            ['name' => 'BURUNDI'],
            ['name' => 'CAMBODIA'],
            ['name' => 'CAMEROON'],
            ['name' => 'CANADA'],
            ['name' => 'CHAD'],
            ['name' => 'CHILE'],
            ['name' => 'CHINA'],
            ['name' => 'COLOMBIA'],
            ['name' => 'COMOROS'],
            ['name' => 'CONGO'],
            ['name' => 'CROATIA'],
            ['name' => 'CUBA'],
            ['name' => 'CYPRUS'],
            ['name' => 'DENMARK'],
            ['name' => 'DJIBOUTI'],
            ['name' => 'DOMINICA'],
            ['name' => 'ECUADOR'],
            ['name' => 'EGYPT'],
            ['name' => 'ERITREA'],
            ['name' => 'ESTONIA'],
            ['name' => 'ETHIOPIA'],
            ['name' => 'FIJI'],
            ['name' => 'FINLAND'],
            ['name' => 'FRANCE'],
            ['name' => 'GABON'],
            ['name' => 'GAMBIA'],
            ['name' => 'GEORGIA'],
            ['name' => 'GERMANY'],
            ['name' => 'GHANA'],
            ['name' => 'GIBRALTAR'],
            ['name' => 'GREECE'],
            ['name' => 'GREENLAND'],
            ['name' => 'GRENADA'],
            ['name' => 'GUADELOUPE'],
            ['name' => 'GUAM'],
            ['name' => 'GUATEMALA'],
            ['name' => 'GUINEA'],
            ['name' => 'GUYANA'],
            ['name' => 'HAITI'],
            ['name' => 'HONDURAS'],
            ['name' => 'HUNGARY'],
            ['name' => 'ICELAND'],
            ['name' => 'INDIA'],
            ['name' => 'INDONESIA'],
            ['name' => 'IRAQ'],
            ['name' => 'IRELAND'],
            ['name' => 'ISRAEL'],
            ['name' => 'ITALY'],
            ['name' => 'JAMAICA'],
            ['name' => 'JAPAN'],
            ['name' => 'JORDAN'],
            ['name' => 'KAZAKHSTAN'],
            ['name' => 'KENYA'],
            ['name' => 'KIRIBATI'],
            ['name' => 'KUWAIT'],
            ['name' => 'KYRGYZSTAN'],
            ['name' => 'LATVIA'],
            ['name' => 'LEBANON'],
            ['name' => 'LESOTHO'],
            ['name' => 'LIBERIA'],
            ['name' => 'LIECHTENSTEIN'],
            ['name' => 'LITHUANIA'],
            ['name' => 'LUXEMBOURG'],
            ['name' => 'MACAO'],
            ['name' => 'MADAGASCAR'],
            ['name' => 'MALAWI'],
            ['name' => 'MALAYSIA'],
            ['name' => 'MALDIVES'],
            ['name' => 'MALI'],
            ['name' => 'MALTA'],
            ['name' => 'MARTINIQUE'],
            ['name' => 'MAURITANIA'],
            ['name' => 'MAURITIUS'],
            ['name' => 'MAYOTTE'],
            ['name' => 'MEXICO'],
            ['name' => 'MONACO'],
            ['name' => 'MONGOLIA'],
            ['name' => 'MONTSERRAT'],
            ['name' => 'MOROCCO'],
            ['name' => 'MOZAMBIQUE'],
            ['name' => 'MYANMAR'],
            ['name' => 'NAMIBIA'],
            ['name' => 'NAURU'],
            ['name' => 'NEPAL'],
            ['name' => 'NETHERLANDS'],
            ['name' => 'NICARAGUA'],
            ['name' => 'NIGER'],
            ['name' => 'NIGERIA'],
            ['name' => 'NIUE'],
            ['name' => 'NORWAY'],
            ['name' => 'OMAN'],
            ['name' => 'PAKISTAN'],
            ['name' => 'PALAU'],
            ['name' => 'PANAMA'],
            ['name' => 'PARAGUAY'],
            ['name' => 'PERU'],
            ['name' => 'PHILIPPINES'],
            ['name' => 'PITCAIRN'],
            ['name' => 'POLAND'],
            ['name' => 'PORTUGAL'],
            ['name' => 'QATAR'],
            ['name' => 'REUNION'],
            ['name' => 'ROMANIA'],
            ['name' => 'RWANDA'],
            ['name' => 'SAMOA'],
            ['name' => 'SENEGAL'],
            ['name' => 'SINGAPORE'],
            ['name' => 'SEYCHELLES'],
            ['name' => 'SLOVAKIA'],
            ['name' => 'SLOVENIA'],
            ['name' => 'SOMALIA'],
            ['name' => 'SPAIN'],
            ['name' => 'SUDAN'],
            ['name' => 'SURINAME'],
            ['name' => 'SWAZILAND'],
            ['name' => 'SWEDEN'],
            ['name' => 'SWITZERLAND'],
            ['name' => 'TAJIKISTAN'],
            ['name' => 'THAILAND'],
            ['name' => 'TOGO'],
            ['name' => 'TOKELAU'],
            ['name' => 'TONGA'],
            ['name' => 'TUNISIA'],
            ['name' => 'TURKEY'],
            ['name' => 'TURKMENISTAN'],
            ['name' => 'TUVALU'],
            ['name' => 'UGANDA'],
            ['name' => 'UKRAINE'],
            ['name' => 'URUGUAY'],
            ['name' => 'UZBEKISTAN'],
            ['name' => 'VANUATU'],
            ['name' => 'VENEZUELA'],
            ['name' => 'YEMEN'],
            ['name' => 'ZAMBIA'],
            ['name' => 'ZIMBABWE']
        ]);
    }
}
